### ISSUE TITLE
Create a tour with https://github.com/gilbarbara/react-joyride

### ISSUE THREAD

**Issue by matmair** [invenhost/InvenTree-react-archive#14]

**Comment by MaYaNkKashyap681** [comment]
I can help you out with this.

**Comment by matmair** [comment]
Thank you @MaYaNkKashyap681  for the offer. I might come back to this at a later point, creating a tour for an empty user interface is a bit pointless I think.
Let‘s talk about this again once #2 is somewhat finished

**Comment by matmair** [comment]
Moved to upstream
