### ISSUE TITLE
Create search UI

### ISSUE THREAD

**Issue by matmair** [invenhost/InvenTree-react-archive#18]

**Comment by MaYaNkKashyap681** [comment]
I want to work on this can i start working

**Comment by matmair** [comment]
@MaYaNkKashyap681 Great! A rough outline of the requirements:
- Quicksearch through the search field on top of the main layout
- No data-fetching till the search is invoked
- Provide a flyout or modal for the main search window
- Provide all the search results that the original interface provides (you can check out the [demo](https://inventree.org/demo) for the current implementation, you will also find the API calls necessary there)
- Please try to only use the depenecies that are already used. Please ping me if you want to add something, I am trying to keep the dependencies slim

Feel free to open a draft PR early on and ping me if you want feedback!

**Comment by MaYaNkKashyap681** [comment]
![Screenshot (101)](https://user-images.githubusercontent.com/96070627/202527140-ef8576b1-5e9d-4637-81fb-ce5a47189daf.png)
<img width="790" alt="Screenshot_20221117_115151" src="https://user-images.githubusercontent.com/96070627/202527151-0963c345-324e-4e78-8ece-4525873eedf3.png">


Do I have to code the UI of these components or something else?
Do you want the search to be done inside the flyout or modal on this page and results to be shown in the same place they are now?

**Comment by matmair** [comment]
First of all sorry for the current (none) state of devdocs or issue content. Did not think someone would want to participate before this gets upstreamed.
As a UI framework the new interface uses Mantine UI - please use the components provided by that. I am not really set on a look, the goal right now is to get a working Proof that covers all the core functions so we can evaluate if this really works as the new UI.

> Do you want the search to be done inside the flyout or modal on this page and results to be shown in the same place they are now?

I imagine having a quick search (for now only searching the parts API route should be fine) in the first part and then have the option to get to a flyout or modal where all categories are explored like in the current UI.

Does not have to be pretty rn - I am currently basically just slapping together components and getting an MVP of the board so that we can gather feedback.

**Comment by MaYaNkKashyap681** [comment]
Do I have to create an entirely different file and implement everything over there?
Can you please tell me in which folder I have to do all this?

**Comment by matmair** [comment]
@MaYaNkKashyap681 just put it in here, if the component gets big we can always refactor it later. The search box is already part of that component so a lot of logic might go there anyway.
https://github.com/invenhost/InvenTree/blob/ea2c33d8425a775fe1128a435b73878af25d4d27/InvenTree/web/src/src/components/nav/HeaderTabs.tsx

**Comment by matmair** [comment]
@MaYaNkKashyap681 just put it in here, if the component gets big we can always refactor it later. The search box is already part of that component so a lot of logic might go there anyway.
https://github.com/invenhost/InvenTree/blob/ea2c33d8425a775fe1128a435b73878af25d4d27/InvenTree/web/src/src/components/nav/HeaderTabs.tsx
