### ISSUE TITLE
Epic: React

### ISSUE THREAD

**Issue by matmair** [invenhost/InvenTree-react-archive#2]
This is an epic for https://github.com/inventree/InvenTree/issues/2789 / https://github.com/inventree/InvenTree/issues/3901

Techstack Devtools:
- Node 18
- Yarn
- Vite
- Eslint https://github.com/invenhost/InvenTree/issues/15
- [x] #21

Techstack UI:
- React
- [Mantine](https://mantine.dev) UI, Hooks, Core, Date
- [mantine datatable](https://github.com/icflorescu/mantine-datatable) for tables
- React Router
- React Query for Api fetching
- Zustand for local state management
- [html5-qrcode](https://www.npmjs.com/package/html5-qrcode) for scanning
- [React Grid Layout](https://github.com/react-grid-layout/react-grid-layout) for Dashboard
- [LingUI JS](https://lingui.js.org/index.html) for translations

Tasks:
- [x] #3
- [x] #4
- [x] #5
- [x] #8
- [x] #25
- [x] #6
- [x] #26
- [x] #28
- [x] #7
- [x] #29
- [x] #13
- [x] #12
- [x] #11
- [x] #10
- [x] #9
- [x] #18
- [x] #27
- [x] #32
- [x] #31
- [x] #30
- [x] #35

Optional:
- [x] #14

**Comment by wolflu05** [comment]
Where is the source code? Is it gone now?

**Comment by matmair** [comment]
@wolflu05 should be there again. Automation reset to upstream ;-(. Thank god for backups.

**Comment by wolflu05** [comment]
I think the best thing would be to create a discussion in this repo to keep this overview issue clean. But cool would be a pr where we can make comments on. Maybe you can create a pr which has no intend to be merged agains a branch on this repo which has the same stand as the old inventree, so the diff shows every of your changes where we can comment on and discuss very easily.

**Comment by wolflu05** [comment]
And another thing I noticed, you are using react router and typescript. Why not using the tanstack router (same guy as who made the query libary). This libary looks awesome and integrates into the typescript ecosystem. You'll never miss something if you move a rout or change the query parameters, because this libary is fully type safety.

**Comment by matmair** [comment]
@wolflu05  see https://github.com/invenhost/InvenTree/issues/37

**Comment by matmair** [comment]
Not stale
