### ISSUE TITLE
[META] Beta discussion

### ISSUE THREAD

**Issue by matmair** [invenhost/InvenTree-react-archive#37]
@wolflu05 We can use this issue for discussion for now. Discussions do not support tasklist etc. so it is a bit inconvenient from a project management perspective.

Q1:
>  @wolflu05 I think the best thing would be to create a discussion in this repo to keep this overview issue clean. But cool would be a pr where we can make comments on. Maybe you can create a pr which has no intend to be merged agains a branch on this repo which has the same stand as the old inventree, so the diff shows every of your changes where we can comment on and discuss very easily.

A PR does not really make sense, the interface is a full rewrite. I am not changing the existing system so the diff would just show a bunch of new files.
I am trying to get all the backend changes upstream as fast as possible.

Q2:
> @wolflu05 And another thing I noticed, you are using react router and typescript. Why not using the tanstack router (same guy as who made the query libary). This libary looks awesome and integrates into the typescript ecosystem. You'll never miss something if you move a rout or change the query parameters, because this libary is fully type safety.

I am not really convinced of tanstack router. I would like to watch it before I switch away from Remix's router stack - that seems to work well for my workplace.

**Comment by wolflu05** [comment]
Ok. Just thought we can directly comment in the new code on a pr, but an issue is also fine. And yeah, I would definitely also need to try tanstack router out my self, but I'm limited in time. From what I saw in a few videos this typesafty looks awesome. But I can understand you, as this package also says beta and you want to use something longer proven.

**Comment by matmair** [comment]
I am not sure if the code is in a stable state right now. I am refactoring nearly every day as I implement more and more of the open FRs for MVP. I create #38 for this now.

My focus right now is on:
- getting a stable file structure
- defining efficient navigation patterns
- building out all core functions
- discovering all missing backend API routes so that I can upstream them
- getting first user feedback
- creating a contribution friendly stack + adding some docs (later state) about that

**Comment by matmair** [comment]
Still open
