### ISSUE TITLE
Add a local cache for lookup of parts, orders etc. and to render hover cards fast

### ISSUE THREAD

**Issue by matmair** [invenhost/InvenTree-react-archive#55]
Add something that uses indexdb to build a local ref db for fast lookups. Maybe [Dixie.js](https://dexie.org/docs/Tutorial/React).

Store everything we need for hovercards in there and plug all queries to the API async in there (results from API requests get written to local storage at the end async).

Items for part table:
part pk/id, name, description, meta section(can be sold, can be purchased), owner(tbd), category

**Comment by matmair** [comment]
@wolflu05 thoughts?

**Comment by wolflu05** [comment]
Sounds like a good idea, if revoking of this cache is handled properly. But I cannot say something of how this works practically because I haven't done this. But the question is, is this really improving performance?

**Comment by matmair** [comment]
@wolflu05 it is mostly about hover cards. Those take around 300ms to load right now, 50ms with caching
